/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppRouteImport } from './routes/app'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExpertRouteImport } from './routes/expert'
import { Route as FarmerRouteImport } from './routes/farmer'
import { Route as StyleguideRouteImport } from './routes/styleguide'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthSignupRouteImport } from './routes/_auth.signup'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAdvisoriesRouteImport } from './routes/app.advisories'
import { Route as AppCropHealthRouteImport } from './routes/app.crop-health'
import { Route as AppFieldsRouteImport } from './routes/app.fields'
import { Route as AppForecastRouteImport } from './routes/app.forecast'
import { Route as AppMapRouteImport } from './routes/app.map'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppSensorsRouteImport } from './routes/app.sensors'
import { Route as AppTrapsRouteImport } from './routes/app.traps'
import { Route as AppValidationRouteImport } from './routes/app.validation'
import { Route as ExpertIndexRouteImport } from './routes/expert.index'
import { Route as ExpertHistoryRouteImport } from './routes/expert.history'
import { Route as ExpertKnowledgeRouteImport } from './routes/expert.knowledge'
import { Route as FarmerIndexRouteImport } from './routes/farmer.index'
import { Route as FarmerAdvisoriesRouteImport } from './routes/farmer.advisories'
import { Route as FarmerAlertsRouteImport } from './routes/farmer.alerts'
import { Route as FarmerFieldsRouteImport } from './routes/farmer.fields'
import { Route as FarmerFollowUpRouteImport } from './routes/farmer.follow-up'
import { Route as FarmerForecastRouteImport } from './routes/farmer.forecast'
import { Route as FarmerPestsRouteImport } from './routes/farmer.pests'
import { Route as FarmerProfileRouteImport } from './routes/farmer.profile'
import { Route as FarmerScanRouteImport } from './routes/farmer.scan'
import { Route as AppFarmsIdRouteImport } from './routes/app.farms.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertRoute = ExpertRouteImport.update({
  id: '/expert',
  path: '/expert',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleguideRoute = StyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvisoriesRoute = AppAdvisoriesRouteImport.update({
  id: '/advisories',
  path: '/advisories',
  getParentRoute: () => AppRoute,
} as any)
const AppCropHealthRoute = AppCropHealthRouteImport.update({
  id: '/crop-health',
  path: '/crop-health',
  getParentRoute: () => AppRoute,
} as any)
const AppFieldsRoute = AppFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => AppRoute,
} as any)
const AppForecastRoute = AppForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSensorsRoute = AppSensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => AppRoute,
} as any)
const AppTrapsRoute = AppTrapsRouteImport.update({
  id: '/traps',
  path: '/traps',
  getParentRoute: () => AppRoute,
} as any)
const AppValidationRoute = AppValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => AppRoute,
} as any)
const ExpertIndexRoute = ExpertIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExpertRoute,
} as any)
const ExpertHistoryRoute = ExpertHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ExpertRoute,
} as any)
const ExpertKnowledgeRoute = ExpertKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => ExpertRoute,
} as any)
const FarmerIndexRoute = FarmerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerAdvisoriesRoute = FarmerAdvisoriesRouteImport.update({
  id: '/advisories',
  path: '/advisories',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerAlertsRoute = FarmerAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerFieldsRoute = FarmerFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerFollowUpRoute = FarmerFollowUpRouteImport.update({
  id: '/follow-up',
  path: '/follow-up',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerForecastRoute = FarmerForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerPestsRoute = FarmerPestsRouteImport.update({
  id: '/pests',
  path: '/pests',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerProfileRoute = FarmerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerScanRoute = FarmerScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => FarmerRoute,
} as any)
const AppFarmsIdRoute = AppFarmsIdRouteImport.update({
  id: '/farms/$id',
  path: '/farms/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/expert': typeof ExpertRouteWithChildren
  '/farmer': typeof FarmerRouteWithChildren
  '/styleguide': typeof StyleguideRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/app/advisories': typeof AppAdvisoriesRoute
  '/app/crop-health': typeof AppCropHealthRoute
  '/app/fields': typeof AppFieldsRoute
  '/app/forecast': typeof AppForecastRoute
  '/app/map': typeof AppMapRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sensors': typeof AppSensorsRoute
  '/app/traps': typeof AppTrapsRoute
  '/app/validation': typeof AppValidationRoute
  '/expert/history': typeof ExpertHistoryRoute
  '/expert/knowledge': typeof ExpertKnowledgeRoute
  '/farmer/advisories': typeof FarmerAdvisoriesRoute
  '/farmer/alerts': typeof FarmerAlertsRoute
  '/farmer/fields': typeof FarmerFieldsRoute
  '/farmer/follow-up': typeof FarmerFollowUpRoute
  '/farmer/forecast': typeof FarmerForecastRoute
  '/farmer/pests': typeof FarmerPestsRoute
  '/farmer/profile': typeof FarmerProfileRoute
  '/farmer/scan': typeof FarmerScanRoute
  '/app/': typeof AppIndexRoute
  '/expert/': typeof ExpertIndexRoute
  '/farmer/': typeof FarmerIndexRoute
  '/app/farms/$id': typeof AppFarmsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof DashboardRoute
  '/styleguide': typeof StyleguideRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/app/advisories': typeof AppAdvisoriesRoute
  '/app/crop-health': typeof AppCropHealthRoute
  '/app/fields': typeof AppFieldsRoute
  '/app/forecast': typeof AppForecastRoute
  '/app/map': typeof AppMapRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sensors': typeof AppSensorsRoute
  '/app/traps': typeof AppTrapsRoute
  '/app/validation': typeof AppValidationRoute
  '/expert/history': typeof ExpertHistoryRoute
  '/expert/knowledge': typeof ExpertKnowledgeRoute
  '/farmer/advisories': typeof FarmerAdvisoriesRoute
  '/farmer/alerts': typeof FarmerAlertsRoute
  '/farmer/fields': typeof FarmerFieldsRoute
  '/farmer/follow-up': typeof FarmerFollowUpRoute
  '/farmer/forecast': typeof FarmerForecastRoute
  '/farmer/pests': typeof FarmerPestsRoute
  '/farmer/profile': typeof FarmerProfileRoute
  '/farmer/scan': typeof FarmerScanRoute
  '/app': typeof AppIndexRoute
  '/expert': typeof ExpertIndexRoute
  '/farmer': typeof FarmerIndexRoute
  '/app/farms/$id': typeof AppFarmsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/expert': typeof ExpertRouteWithChildren
  '/farmer': typeof FarmerRouteWithChildren
  '/styleguide': typeof StyleguideRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/app/advisories': typeof AppAdvisoriesRoute
  '/app/crop-health': typeof AppCropHealthRoute
  '/app/fields': typeof AppFieldsRoute
  '/app/forecast': typeof AppForecastRoute
  '/app/map': typeof AppMapRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sensors': typeof AppSensorsRoute
  '/app/traps': typeof AppTrapsRoute
  '/app/validation': typeof AppValidationRoute
  '/expert/history': typeof ExpertHistoryRoute
  '/expert/knowledge': typeof ExpertKnowledgeRoute
  '/farmer/advisories': typeof FarmerAdvisoriesRoute
  '/farmer/alerts': typeof FarmerAlertsRoute
  '/farmer/fields': typeof FarmerFieldsRoute
  '/farmer/follow-up': typeof FarmerFollowUpRoute
  '/farmer/forecast': typeof FarmerForecastRoute
  '/farmer/pests': typeof FarmerPestsRoute
  '/farmer/profile': typeof FarmerProfileRoute
  '/farmer/scan': typeof FarmerScanRoute
  '/_public/': typeof PublicIndexRoute
  '/app/': typeof AppIndexRoute
  '/expert/': typeof ExpertIndexRoute
  '/farmer/': typeof FarmerIndexRoute
  '/app/farms/$id': typeof AppFarmsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/dashboard'
    | '/expert'
    | '/farmer'
    | '/styleguide'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/app/advisories'
    | '/app/crop-health'
    | '/app/fields'
    | '/app/forecast'
    | '/app/map'
    | '/app/reports'
    | '/app/sensors'
    | '/app/traps'
    | '/app/validation'
    | '/expert/history'
    | '/expert/knowledge'
    | '/farmer/advisories'
    | '/farmer/alerts'
    | '/farmer/fields'
    | '/farmer/follow-up'
    | '/farmer/forecast'
    | '/farmer/pests'
    | '/farmer/profile'
    | '/farmer/scan'
    | '/app/'
    | '/expert/'
    | '/farmer/'
    | '/app/farms/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/styleguide'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/app/advisories'
    | '/app/crop-health'
    | '/app/fields'
    | '/app/forecast'
    | '/app/map'
    | '/app/reports'
    | '/app/sensors'
    | '/app/traps'
    | '/app/validation'
    | '/expert/history'
    | '/expert/knowledge'
    | '/farmer/advisories'
    | '/farmer/alerts'
    | '/farmer/fields'
    | '/farmer/follow-up'
    | '/farmer/forecast'
    | '/farmer/pests'
    | '/farmer/profile'
    | '/farmer/scan'
    | '/app'
    | '/expert'
    | '/farmer'
    | '/app/farms/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/app'
    | '/dashboard'
    | '/expert'
    | '/farmer'
    | '/styleguide'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/signup'
    | '/app/advisories'
    | '/app/crop-health'
    | '/app/fields'
    | '/app/forecast'
    | '/app/map'
    | '/app/reports'
    | '/app/sensors'
    | '/app/traps'
    | '/app/validation'
    | '/expert/history'
    | '/expert/knowledge'
    | '/farmer/advisories'
    | '/farmer/alerts'
    | '/farmer/fields'
    | '/farmer/follow-up'
    | '/farmer/forecast'
    | '/farmer/pests'
    | '/farmer/profile'
    | '/farmer/scan'
    | '/_public/'
    | '/app/'
    | '/expert/'
    | '/farmer/'
    | '/app/farms/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ExpertRoute: typeof ExpertRouteWithChildren
  FarmerRoute: typeof FarmerRouteWithChildren
  StyleguideRoute: typeof StyleguideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert': {
      id: '/expert'
      path: '/expert'
      fullPath: '/expert'
      preLoaderRoute: typeof ExpertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer': {
      id: '/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/advisories': {
      id: '/app/advisories'
      path: '/advisories'
      fullPath: '/app/advisories'
      preLoaderRoute: typeof AppAdvisoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crop-health': {
      id: '/app/crop-health'
      path: '/crop-health'
      fullPath: '/app/crop-health'
      preLoaderRoute: typeof AppCropHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fields': {
      id: '/app/fields'
      path: '/fields'
      fullPath: '/app/fields'
      preLoaderRoute: typeof AppFieldsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/forecast': {
      id: '/app/forecast'
      path: '/forecast'
      fullPath: '/app/forecast'
      preLoaderRoute: typeof AppForecastRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/map': {
      id: '/app/map'
      path: '/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sensors': {
      id: '/app/sensors'
      path: '/sensors'
      fullPath: '/app/sensors'
      preLoaderRoute: typeof AppSensorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/traps': {
      id: '/app/traps'
      path: '/traps'
      fullPath: '/app/traps'
      preLoaderRoute: typeof AppTrapsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/validation': {
      id: '/app/validation'
      path: '/validation'
      fullPath: '/app/validation'
      preLoaderRoute: typeof AppValidationRouteImport
      parentRoute: typeof AppRoute
    }
    '/expert/': {
      id: '/expert/'
      path: '/'
      fullPath: '/expert/'
      preLoaderRoute: typeof ExpertIndexRouteImport
      parentRoute: typeof ExpertRoute
    }
    '/expert/history': {
      id: '/expert/history'
      path: '/history'
      fullPath: '/expert/history'
      preLoaderRoute: typeof ExpertHistoryRouteImport
      parentRoute: typeof ExpertRoute
    }
    '/expert/knowledge': {
      id: '/expert/knowledge'
      path: '/knowledge'
      fullPath: '/expert/knowledge'
      preLoaderRoute: typeof ExpertKnowledgeRouteImport
      parentRoute: typeof ExpertRoute
    }
    '/farmer/': {
      id: '/farmer/'
      path: '/'
      fullPath: '/farmer/'
      preLoaderRoute: typeof FarmerIndexRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/advisories': {
      id: '/farmer/advisories'
      path: '/advisories'
      fullPath: '/farmer/advisories'
      preLoaderRoute: typeof FarmerAdvisoriesRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/alerts': {
      id: '/farmer/alerts'
      path: '/alerts'
      fullPath: '/farmer/alerts'
      preLoaderRoute: typeof FarmerAlertsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/fields': {
      id: '/farmer/fields'
      path: '/fields'
      fullPath: '/farmer/fields'
      preLoaderRoute: typeof FarmerFieldsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/follow-up': {
      id: '/farmer/follow-up'
      path: '/follow-up'
      fullPath: '/farmer/follow-up'
      preLoaderRoute: typeof FarmerFollowUpRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/forecast': {
      id: '/farmer/forecast'
      path: '/forecast'
      fullPath: '/farmer/forecast'
      preLoaderRoute: typeof FarmerForecastRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/pests': {
      id: '/farmer/pests'
      path: '/pests'
      fullPath: '/farmer/pests'
      preLoaderRoute: typeof FarmerPestsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/profile': {
      id: '/farmer/profile'
      path: '/profile'
      fullPath: '/farmer/profile'
      preLoaderRoute: typeof FarmerProfileRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/scan': {
      id: '/farmer/scan'
      path: '/scan'
      fullPath: '/farmer/scan'
      preLoaderRoute: typeof FarmerScanRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/app/farms/$id': {
      id: '/app/farms/$id'
      path: '/farms/$id'
      fullPath: '/app/farms/$id'
      preLoaderRoute: typeof AppFarmsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AppRouteChildren {
  AppAdvisoriesRoute: typeof AppAdvisoriesRoute
  AppCropHealthRoute: typeof AppCropHealthRoute
  AppFieldsRoute: typeof AppFieldsRoute
  AppForecastRoute: typeof AppForecastRoute
  AppMapRoute: typeof AppMapRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSensorsRoute: typeof AppSensorsRoute
  AppTrapsRoute: typeof AppTrapsRoute
  AppValidationRoute: typeof AppValidationRoute
  AppIndexRoute: typeof AppIndexRoute
  AppFarmsIdRoute: typeof AppFarmsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdvisoriesRoute: AppAdvisoriesRoute,
  AppCropHealthRoute: AppCropHealthRoute,
  AppFieldsRoute: AppFieldsRoute,
  AppForecastRoute: AppForecastRoute,
  AppMapRoute: AppMapRoute,
  AppReportsRoute: AppReportsRoute,
  AppSensorsRoute: AppSensorsRoute,
  AppTrapsRoute: AppTrapsRoute,
  AppValidationRoute: AppValidationRoute,
  AppIndexRoute: AppIndexRoute,
  AppFarmsIdRoute: AppFarmsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ExpertRouteChildren {
  ExpertHistoryRoute: typeof ExpertHistoryRoute
  ExpertKnowledgeRoute: typeof ExpertKnowledgeRoute
  ExpertIndexRoute: typeof ExpertIndexRoute
}

const ExpertRouteChildren: ExpertRouteChildren = {
  ExpertHistoryRoute: ExpertHistoryRoute,
  ExpertKnowledgeRoute: ExpertKnowledgeRoute,
  ExpertIndexRoute: ExpertIndexRoute,
}

const ExpertRouteWithChildren =
  ExpertRoute._addFileChildren(ExpertRouteChildren)

interface FarmerRouteChildren {
  FarmerAdvisoriesRoute: typeof FarmerAdvisoriesRoute
  FarmerAlertsRoute: typeof FarmerAlertsRoute
  FarmerFieldsRoute: typeof FarmerFieldsRoute
  FarmerFollowUpRoute: typeof FarmerFollowUpRoute
  FarmerForecastRoute: typeof FarmerForecastRoute
  FarmerPestsRoute: typeof FarmerPestsRoute
  FarmerProfileRoute: typeof FarmerProfileRoute
  FarmerScanRoute: typeof FarmerScanRoute
  FarmerIndexRoute: typeof FarmerIndexRoute
}

const FarmerRouteChildren: FarmerRouteChildren = {
  FarmerAdvisoriesRoute: FarmerAdvisoriesRoute,
  FarmerAlertsRoute: FarmerAlertsRoute,
  FarmerFieldsRoute: FarmerFieldsRoute,
  FarmerFollowUpRoute: FarmerFollowUpRoute,
  FarmerForecastRoute: FarmerForecastRoute,
  FarmerPestsRoute: FarmerPestsRoute,
  FarmerProfileRoute: FarmerProfileRoute,
  FarmerScanRoute: FarmerScanRoute,
  FarmerIndexRoute: FarmerIndexRoute,
}

const FarmerRouteWithChildren =
  FarmerRoute._addFileChildren(FarmerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ExpertRoute: ExpertRouteWithChildren,
  FarmerRoute: FarmerRouteWithChildren,
  StyleguideRoute: StyleguideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
